# Generated by Django 4.2.30 on 2026-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
